CREATE TABLE [dbo].[DocumentoSalida] (
    [NroSalida]             INT           IDENTITY (1, 1) NOT NULL,
    [CodAlmacen]            VARCHAR (3)   NOT NULL,
    [NroDocSalida]          VARCHAR (20)  NOT NULL,
    [CodEstadoSalida]       CHAR (1)      CONSTRAINT [DF_DS_CodEstadoSalida] DEFAULT ('N') NOT NULL,
    [NroDocReferencia]      VARCHAR (7)   NULL,
    [CodDocSalida]          SMALLINT      NOT NULL,
    [CodCliente]            VARCHAR (20)  NULL,
    [CodDestinatario]       VARCHAR (12)  NULL,
    [NomDestinatario]       VARCHAR (100) NULL,
    [DireccionDestino]      VARCHAR (60)  NULL,
    [CiudadDestino]         VARCHAR (50)  NULL,
    [Observaciones]         VARCHAR (255) NULL,
    [PaisDestino]           VARCHAR (30)  NULL,
    [CodAlmacenDestino]     VARCHAR (3)   NULL,
    [FechaEstimadaDespacho] DATETIME      NULL,
    [FechaPreparado]        DATETIME      NULL,
    [FechaEmpaque]          DATETIME      NULL,
    [FechaCarga]            DATETIME      NULL,
    [FechaRealDespacho]     DATETIME      NULL,
    [NroPatente]            VARCHAR (15)  NULL,
    [Prioridad]             SMALLINT      NOT NULL,
    [PickingPorOla]         CHAR (1)      DEFAULT ('N') NULL,
    [BackOrder]             VARCHAR (15)  NULL,
    [NroDocEntrada]         VARCHAR (20)  NULL,
    [FechaCreacion]         DATETIME      NULL,
    [UsuarioCreacion]       VARCHAR (20)  NULL,
    [FechaModificacion]     DATETIME      NULL,
    [UsuarioModificacion]   VARCHAR (20)  NULL,
    CONSTRAINT [PK_DocumentoSalida] PRIMARY KEY CLUSTERED ([NroSalida] ASC, [CodAlmacen] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DocSalida_Almacen] FOREIGN KEY ([CodAlmacen]) REFERENCES [dbo].[Almacen] ([CodAlmacen]),
    CONSTRAINT [FK_DocumentoSalida_Cliente] FOREIGN KEY ([CodCliente]) REFERENCES [dbo].[Cliente] ([CodCliente])
);

